### PR TITLE
Replace bat- and syntect-based tests with in-repo test crate

### PR DESCRIPTION
**Pull request by Enselic**
And build rustdoc JSON inside of `cargo test` instead of using pre-built
rustdoc JSON that we version in git. This has several advantages:

* It becomes much easier to add regression tests since we have a
  test-crate we can add a public item to

* The git repo becomes smaller since it is not filled with large amounts
  of raw rustdoc JSON.

* We remove the need to be in possession of bat and syntect source code
  (to update the rustdoc JSON)

* We improve code coverage of the library code by quite a bit in
  relevant files. See below:

Code coverage sample before this commit:
```
Filename                         Regions Covered
--------------------------------------------------
intermediate_public_item.rs      78.53%
item_iterator.rs                 92.86%
```

after this commit:
```
Filename                         Regions Covered
--------------------------------------------------
intermediate_public_item.rs      84.29%
item_iterator.rs                 94.29%
```

The down-side is that we lose the benefit of testing against actual,
non-trivial, real-world public APIs. But I think we can compensate for
that.

### CODE REVIEW

**Comment by Enselic** [comment]
CC @douweschulte because this makes it much easier to add regression tests in the future, so it is good to know about.

I dry-merged with your own `main` branch, and the only conflicts were in `Cargo.lock`, so I went ahead and merged this PR.

**Comment by douweschulte** [comment]
Nice, about changes in `Cargo.lock` it is customary to not track those in a library( `crates.io` also does not expose it to crate users) because a library should be less strictly dependent on a specific version of a crate. In the best case this would allow cargo in user projects to have more flexibility in selecting crates versions and so less versions of a single library in the final compilation. I recently learned this and respecified all my dependencies for my own crate to allow for a more flexible selection. There even is the option (in nightly) to test the compilation with minimal versions: [https://doc.rust-lang.org/cargo/reference/unstable.html#minimal-versions].

See [cargo FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).
See [my own cargo.toml](https://github.com/douweschulte/pdbtbx/blob/master/Cargo.toml).

**Comment by Enselic** [comment]
Thank you for the tip. I was actually aware of the "no Cargo.lock for libraries rule", but I was thinking that since my project includes the thin `public_items` bin, I should version-control Cargo.lock. I noticed you do not have any bin in https://github.com/douweschulte/pdbtbx, so in that case it is an easy choice to not version-control `Cargo.lock`. Do you know best practice in case a package has both a bin and a lib?

BTW, the new test setup with the `comprehensive_api` that this PR introduced made me quickly find and fix 5 bugs + regression tests, and it was a breeze: https://github.com/Enselic/public_items/pull/57

(I again made sure that the PR did not create any merge conflicts with your code.)

I'd like to make some more improvements to tests, but as soon as I feel done with that I will take a closer look at your draft PR. I've skimmed it through and it looks very reasonable on a high level. I hope to be able to come back to you with some constructive comments in a not too long while.

**Comment by douweschulte** [comment]
I am not really sure in the case of a bin + lib. And really nice that this PR makes these things easier, I will look into it as well then. Looking forward to your feedback.

**Pull request merged**
